language: node_js
node_js:
  - node
env:
  - WEXT_SHIPIT_CHROME_EXTENSION_ID=ignndocldlheghlflchdbokagecncgmm
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master
      tags: true
