language: node_js
node_js:
  - node
script: npm run build
env:
  - EXTENSION_ID=ignndocldlheghlflchdbokagecncgmm
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master
      tags: true
